# Generated by Django 4.1.3 on 2022-11-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('work', models.CharField(max_length=50)),
                ('answer1', models.CharField(max_length=50)),
                ('answer2', models.CharField(max_length=50)),
                ('answer3', models.CharField(max_length=50)),
                ('answer4', models.CharField(max_length=50)),
                ('answer5', models.CharField(max_length=50)),
                ('answer6', models.CharField(max_length=50)),
                ('answer7', models.CharField(max_length=50)),
                ('answer8', models.CharField(max_length=50)),
                ('answer9', models.CharField(max_length=50)),
                ('answer10', models.CharField(max_length=50)),
                ('answer11', models.CharField(max_length=50)),
                ('answer12', models.CharField(max_length=50)),
                ('answer13', models.CharField(max_length=50)),
                ('answer14', models.CharField(max_length=50)),
                ('answer15', models.CharField(max_length=50)),
                ('answer16', models.CharField(max_length=50)),
                ('answer17', models.CharField(max_length=50)),
                ('answer18', models.CharField(max_length=50)),
                ('answer19', models.CharField(max_length=50)),
                ('answer20', models.CharField(max_length=50)),
                ('answer21', models.CharField(max_length=50)),
                ('answer22', models.CharField(max_length=50)),
                ('answer23', models.CharField(max_length=50)),
                ('answer24', models.CharField(max_length=50)),
                ('answer25', models.CharField(max_length=50)),
                ('answer26', models.CharField(max_length=50)),
                ('answer27', models.CharField(max_length=50)),
                ('answer28', models.CharField(max_length=50)),
                ('answer29', models.CharField(max_length=50)),
                ('answer31', models.CharField(max_length=50)),
                ('answer32', models.CharField(max_length=50)),
                ('answer33', models.CharField(max_length=50)),
                ('answer34', models.CharField(max_length=50)),
                ('answer35', models.CharField(max_length=50)),
            ],
        ),
    ]
