# Generated by Django 4.1.3 on 2022-11-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPsy', '0006_quests_right_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quests',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
